### ISSUE TITLE
list of topics

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/geogeeks#3]
My proposal:

### Basic of computing

  - filesystem

### C++

  - CLion
  - Using WSL
  - CMake help
  - Useful libaries for geomatics engineers

### Geomatics software

  - not sure I guess some relevant software
  - QGIS plugins?

### git

  - Intro to git
  - A good git repo
  - How to collaborate with git (PR, issues, etc.)
  - GitHub Actions

### How to do research

  - some research tips
  - how to Google Scholar
  - JabRef tips

### Linux

  - Intro to the shell
  - ssh to linux server
  - WSL 
  - installing libraries and packages

### Python

  - virtual env 
  - A good Python setup
  - Useful libaries for geomatics engineers

### The best...

  - Each staff can list their "best to do X" software:
    - text editor
    - git client
    - C++ editor
    - Python editor
    - LaTeX editor
    - GIS
    - etc.

### Web

  - ?

### Writing

  - LaTeX
  - Markdown
  - Tips for making figures
  - Collaborative writing

**Comment by mdjong1** [comment]
Would it be alright if I split this out into separate issues per heading? Would make it satisfying when you pick something and can close an issue afterwards

**Comment by hugoledoux** [comment]
oh wow, I didn't think an ex-student would get involved, but you're very much welcome to help!

Yes sure I see your point here, I'll give you admin
